import aiGateway from "../ai/gateway/aiGateway.js";
import { validateGeneratedQuestions } from "./questionValidationService.js";

/* ------------------ helpers ------------------ */

const toNumber = (value, fallback) => {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
};

const normalizeQuestion = (question, index) => {
  const optionsRaw = Array.isArray(question?.options) ? question.options : [];
  const options = optionsRaw.map((o) => String(o ?? "")).slice(0, 4);

  while (options.length < 4) options.push("");

  const correct = toNumber(question?.correct, 0);
  const safeCorrect = correct >= 0 && correct < 4 ? correct : 0;

  return {
    id: String(question?.id || `q_${index + 1}`),
    question: String(question?.question || ""),
    options,
    correct: safeCorrect,
    correctAnswer: question?.correctAnswer ? String(question.correctAnswer) : options[safeCorrect],
    explanation: String(question?.explanation || ""),
    difficulty: String(question?.difficulty || "medium"),
  };
};

const normalizeQuestionSet = (questions) =>
  (Array.isArray(questions) ? questions : []).map(normalizeQuestion);

/* ------------------ fallback (generic only) ------------------ */

const genericFallback = (count) => {
  const safeCount = Math.max(1, toNumber(count, 10));
  const base = [
    {
      question: "Which option is correct?",
      options: ["Option A", "Option B", "Option C", "Option D"],
      correct: 0,
    },
  ];

  return Array.from({ length: safeCount }, (_, i) =>
    normalizeQuestion(
      {
        ...base[i % base.length],
        id: `q_${i + 1}`,
      },
      i
    )
  );
};

/* ------------------ main service ------------------ */

export const generateQuizQuestions = async ({
  subject,
  materialText = "",
  questions,
  difficulty = "mixed",
  classification,
  classificationSource,
  externalAIAllowed,
  allowFallback = false,
  competencyIds = [],
  targetProficiencyLevel = 3,
  questionType = "knowledge",
  sourceReference = "",
  language = "en", // Default to English, can be hi, mr, etc.
  competencyId = null,
  competencyName = null,
  competencyCode = null,
  topic = null,
}) => {
  const safeCount = Math.max(1, toNumber(questions, 10));
  const safeDifficulty = "mixed";
  const safeSubject = String(subject || "general").trim();

  const sourceText = String(materialText || subject).replace(/\s+/g, " ").trim().slice(0, 12000);
  const maxTokens = Math.min(4096, Math.max(1024, safeCount * 300));

  // Language-specific instructions
  const languageInstructions = {
    en: "Generate questions in English",
    hi: "Generate questions in Hindi (हिंदी)",
    mr: "Generate questions in Marathi (मराठी)",
  };

  const languageInstruction = languageInstructions[language] || languageInstructions.en;

  const prompt = `
Generate ${safeCount} competency-aware multiple-choice questions strictly based on:
"${safeSubject}"

${languageInstruction}

Source material:
${sourceText}

Difficulty: mixed; include a balanced mix of easy, medium, and hard questions; target proficiency level: ${targetProficiencyLevel}; type: ${questionType}.
Allowed competency IDs: ${competencyIds.map(String).join(", ")}

Rules:
- Questions must ONLY belong to the given subject/topic
- 4 options exactly
- One correct answer
- Include a brief explanation, competencyId, targetProficiencyLevel, difficulty, questionType and sourceReference for each question
- No extra text
- Output ONLY valid JSON in the format below

{
  "questions": [
    {
      "id": "q1",
      "question": "",
      "options": ["", "", "", ""],
        "correct": 0,
        "explanation": "",
        "difficulty": "medium", "competencyId": "", "targetProficiencyLevel": 3, "questionType": "knowledge", "sourceReference": ""
    }
  ]
}
`;

  try {
    // Competency assessments are always generated by the configured local
    // Ollama model.  Do not route this workflow through the legacy provider
    // abstraction because it may select an external fallback.
    const aiResponse = await aiGateway.generateStructured({
      capability: "competency_assessment_generation",
      content: prompt,
      classification: classification || "CATEGORY_A_OPEN_ACCESS",
      classificationSource: classificationSource || "ORGANIZATION_POLICY",
      externalAIAllowed: false,
      forcePrivate: true,
      preferredProvider: "ollama",
      systemPrompt: "You generate grounded competency assessment questions. Return JSON only.",
      schema: { questions: "array" },
      maxTokens,
      temperature: 0.2,
    });

    if (aiResponse.success && Array.isArray(aiResponse.data?.questions)) {
      const validated = await validateGeneratedQuestions(aiResponse.data.questions, { 
        allowedCompetencyIds: competencyIds, 
        defaultCompetencyId: competencyIds[0],
        requireCompetency: competencyIds.length > 0,
        defaultLevel: targetProficiencyLevel, 
        sourceReference 
      });
      
      if (validated.length > 0) {
        return validated.slice(0, safeCount).map((question) => ({ 
          ...question, 
          id: question.questionId, 
          correct: question.correctAnswer 
        }));
      }

      throw new Error("AI provider returned no valid quiz questions.");
    }

    const aiError = aiResponse.error || aiResponse.reason || "AI quiz generation failed.";
    if (!allowFallback) throw new Error(aiError);
    console.warn("AI Provider quiz generation failed:", aiError);
  } catch (error) {
    if (!allowFallback) throw error;
    console.error("AI Provider error:", error.message);
  }

    throw new Error("AI quiz generation failed validation; no draft was saved.");
};

export default generateQuizQuestions;
